### PR TITLE
feat: get products

### PR DESCRIPTION
**Pull request by maximwow70**

### CODE REVIEW

**Comment by Inga-Vishnivetskaia** [comment]
Hi! 
70 score: getProductsById AND getProductsList lambda functions return a correct response code, FE is integrated with getProductsList
+5 ⭐ - ES6 modules are used for Product Service implementation
+4  - SWAGGER documentation is created for Product Service 👍 
+4  - Lambda handlers (getProductsList, getProductsById) code is written not in 1 single module (file) and separated in codebase. 👍 
+4 - Main error scenarios are handled by API ("Product not found" error). 👍 
currently have total 87, I don't see the actual use of async await in the code, there is no async operation currently as we are getting mock data. Maybe it can be put to S3 bucket in order to get an async operation. 🤔

**Comment by maximwow70** [comment]
Hi, `I don't see the actual use of async await in the code`:
does it means that I should create some "database" service which provide mocked products as Promise?

**Comment by Inga-Vishnivetskaia** [comment]
As an option to put it in S3 bucket or maybe just wrap in Promise is enough, there is no clear criteria in task description

**Comment by maximwow70** [comment]
Added, thanks!

**Pull request merged**
